### ISSUE TITLE
使用腾讯云COS存储如何配置图片URL

### ISSUE THREAD

**Issue by TheLuminary** [sysucats/zhongdamaopu#30]
前三步检查均已通过，我确认Laf后台的各个环境变量配置正确，
`use_private_tencent_cos: true`
`系统`目录已经通过腾讯云控制台上传到COS，小程序`config.js`中的各个图片链接究竟应该如何配置？下面两种好像都不正确，均不能通过第四步检查……
`https://cats-1234567890.cos.ap-beijing.myqcloud.com/系统/菊花码.jpg`
`https://cos.ap-beijing.myqcloud.com/cats-1234567890/系统/菊花码.jpg`
（其中`1234567890`为APPID，在我的配置中为真实的APPID）

望予以帮助，谢谢！

**Comment by TheLuminary** [comment]
本质原因及Bugfix如 #31

**Comment by Zing22** [comment]
赞！辛苦了
